### ISSUE TITLE
GH API rate limiting (+ pagination)

### ISSUE THREAD

**Issue by gaborcsardi** [nikeee/setup-pandoc#1]
The hosted VMs do not have a lot of IP addresses, so if you are calling the GH API without a token, then you'll be rate limited.

The other potential issue is that there is no documented order for the releases, so you might need to paginate. There is an endpoint for the latest release (https://docs.github.com/en/rest/reference/releases#get-the-latest-release I _think_ this) but I am not entirely sure if this is the one you'd want, if pandoc creates releases for older branches.

**Comment by nikeee** [comment]
> but I am not entirely sure if this is the one you'd want,

The original intention was to offer the user the ability to specify a semver spec for their rewuired version (for example, `^2.17`). However, this did not work out as pandoc does not use proper semver. Also, I assumed the order to be defined (the projects I looked at always had the same order as on the website). But you're right, technically, it's not specified (at least I, too, could not find any information on that).


Using the `latest` endpoint would be the correct thing to do here.
The Pandoc website currently points to `https://github.com/jgm/pandoc/releases/latest` as a download link to the "latest installer". I am assuming that this is the same release that the API will point to, so this might be stable for long enough for us.

I could not find any reliable information on rate limits of unauthenticated requests. However, the thing that would probably solve these issues would using the [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).

**Comment by gaborcsardi** [comment]
> I could not find any reliable information on rate limits of unauthenticated requests. However, the thing that would probably solve these issues would using the [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

60 requests per hour
